[package]
name = "openhmd-chat"
version = "0.1.0"
authors = ["TheHellBox <hellboxstudio@yandex.ru>"]

[dependencies]
openhmd-rs="*"
alto="3.0.1"
cobalt="*"
opus="*"
serde="1.0"
serde_derive = "1.0"
bincode="1.0"
clap="*"
glium="*"
tobj="*"
image="*"
