[package]
name = "openhmd-chat"
version = "0.1.1"
authors = ["TheHellBox <thehellbox11@gmail.com>"]

[dependencies]
glium="*"
openhmd-rs="0.1.4"
tobj="*"
image = "*"
nalgebra="*"
cobalt = "0.22.0"
bytevec="*"
rand="*"
alto="*"
gilrs="*"
opus="*"
