[package]
name = "openhmd-chat-server"
version = "0.1.0"
authors = ["TheHellBox <hellboxstudio@yandex.ru>"]

[dependencies]
cobalt="*"
serde="1.0"
serde_derive = "1.0"
bincode="1.0"
nalgebra={ version = "0.15", features = ["serde-serialize"] }
hlua="0.4"
rand="*"
lazy_static = "1.1.0"
